"""revetir cambios

Revision ID: 5b5dc2d7460f
Revises: b9a02311f62e
Create Date: 2026-02-25 20:25:38.685824

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5b5dc2d7460f'
down_revision = 'b9a02311f62e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alumnos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('apaterno', sa.String(length=50), nullable=True))
        batch_op.drop_column('apellidos')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alumnos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('apellidos', mysql.VARCHAR(length=200), nullable=True))
        batch_op.drop_column('apaterno')

    # ### end Alembic commands ###
